### ISSUE TITLE
It is difficult to training

### ISSUE THREAD

**Issue by harukaza** [phellonchen/DMRM#2]
I clone the code from source for training. And I found the result in v1.0 were bad.

_Epoch 12: mrr: 0.425225 R1: 0.326793 R5 0.512984 R10 0.560126 Mean 23.555378 time: 112.83
Epoch 13: mrr: 0.425715 R1: 0.326793 R5 0.514390 R10 0.561240 Mean 23.428488 time: 117.13
Epoch 14: mrr: 0.425800 R1: 0.326502 R5 0.514583 R10 0.561531 Mean 23.346754 time: 117.97_  

then the model stop training.

how to get the same result in your paper

**Comment by chensihang1** [comment]
Me too

**Comment by phellonchen** [comment]
Note that we only test the code on Pytorch v0.3.0 and it may dose not work on other versions.  I'll very busy now and I will re-check the code as soon as possible.  Sorry about that.
